apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-golang
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-golang
    spec:
      containers:
      - name: hello-golang
        image: localhost:5000/hello-golang:1.0
